WITH DB_COST AS (
	SELECT
		OMITNO AS Item
		, OMSAPR AS DB_COST
	FROM
		MVXBDTA888.SIPRIL
	WHERE
		OMCUCD = 'CNY'
		AND OMPRS1 = 'M1'
)
, List_Price AS (
	SELECT
		OMITNO AS Item
		, OMSAPR AS List_Price
	FROM
		MVXBDTA888.SIPRIL
	WHERE
		OMCUCD = 'CNY'
		AND OMPRS1 = 'MA'
)
, Price_MG AS (
	SELECT
		OMITNO AS Item
		, OMSAPR AS MG_GROUP_Pirce
	FROM
		MVXBDTA888.SIPRIL
	WHERE
		OMCUCD = 'CNY'
		AND OMPRS1 = 'MG'
)
, Chinese AS (
	SELECT
		MDITNO AS PN
		, MDITDS AS Name_Chinese
	FROM
		MVXBDTA888.MITLAD
	WHERE
		MDLNCD = 'CS'
)
,
English AS 
	SELECT
		MDITNO AS PN
		, MDITDS AS Name_English
	FROM
		MVXBDTA888.MITLAD
	WHERE
		MDLNCD = 'GB'
)
SELECT
	DISTINCT 
	Curdate()
	, T01.OMITNO AS Item
	, T03.MMITDS AS Description
	, Name_Chinese
	, Name_English
	, T01.OMCUCD AS Currency
	, DB_COST
	, List_Price
	, T04.MG_GROUP_Pirce
	, T03.MMSTAT AS Status
	, T03.MMITGR AS Item_GRP
	, T03.MMITCL AS Product_GRP
FROM
	MVXBDTA888.SIPRIL AS T01
LEFT JOIN DB_COST ON
	DB_COST.Item = T01.OMITNO
LEFT JOIN List_Price ON
	List_Price.Item = T01.OMITNO
LEFT JOIN Chinese AS T002 ON
	T01.OMITNO = T002.PN
LEFT JOIN English AS T003 ON
	T01.OMITNO = T003.PN
LEFT JOIN MVXBDTA888.MITMAS AS T03 ON
	T01.OMITNO = T03.MMITNO
LEFT JOIN Price_MG AS T04 ON
	T04.Item = t01.OMITNO
WHERE
	T01.OMCUCD = 'CNY'